<?php

namespace AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

    private $select = 'cat.libelle as catName, v.libelle as villeName';



    public function findCatByid($tag)
    {


        $qb = $this->createQueryBuilder("u")
            ->Join("AdminBundle:Ngn", 'n' ,"with","n.category = u.id")
            ->Join("AdminBundle:Qouiqui", "qq" ,"with","n.qouiqui = qq.id")
            ->where("qq.id= :tag")
            ->setParameter('tag', $tag);

        return $qb->getQuery()->getSingleResult();

    }



}

