<?php

namespace AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventsRepository extends EntityRepository
{

    public function findEvents()
    {
        $tag=new \DateTime();
        $qb = $this->createQueryBuilder("u");
        $qb ->Where('u.dateEnd >= :myTag')
            ->orderBy('u.dateEnd', 'DESC')
            ->setParameter('myTag', $tag)
            ->setMaxResults(3);

        return $qb->getQuery()->getResult();

    }

    public function findEventsByQQ($id)
    {

        $qb = $this->createQueryBuilder("u");
        $qb ->join('u.qville' , 'q')
            ->join('q.qouiqui','qq')
            ->Where('qq.id = :myTag')
            ->setParameter('myTag', $id);

        return $qb->getQuery()->getResult();

    }
}

