<?php

namespace AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;



/**
 * userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */





class QvilleRepository extends EntityRepository
{

    public function findQQbyville($tag)
    {



//        $qb=$this->createQueryBuilder("u");
//        $qb->join("u.qouiqui", "qq",null,null,"QOUIQUI_id");
//        $qb->join("u.ville", "v",null,null,"VILLE_id");
//        $qb->where("v.id = 5");

        $qb=$this->createQueryBuilder("u")
        ->Join("AdminBundle:Qouiqui", "qq" , "with" ,"qq.id = u.qouiqui")
        ->Join("AdminBundle:Ngn", "g" , "with" ,"g.id = g.qouiqui")
        ->where("g.category = 1");



//        if ($tag["ville"] != null){
//            $qb->where("v.libelle like '%Goa%'");
//
////                ->setParameter('tag_ville_param', "'%".$tag["ville"]."%'");
//        }

//        $qb->where("u.name like :tag_param")
//            ->setParameter('tag_param', "'%".$tag["ville"]."%'");
        return $qb->getQuery()->getResult();

    }


}

