<?php

namespace AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;



/**
 * userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */





class ReviewsRepository extends EntityRepository
{

    public function findReviewsByqq($tag)
    {

        $qb=$this->createQueryBuilder("u")
        ->Join("AdminBundle:Qouiqui", "qq", "with" , "u.qouiqui =qq.id")
        ->where('u.qouiqui=:Tag')
        ->orderBy('u.id', 'DESC')
        ->setParameter('Tag',$tag);

        return $qb->getQuery()->getResult();

    }


}

