imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AdminBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@DashboardBundle/Resources/config/services.yml" }
    - { resource: "@ModuleBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    images_directory: '%kernel.root_dir%/../web/uploads/image'
    uploads_directory: '%kernel.root_dir%/../web/uploads/'
    locale: fr



framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
        name: SFSESSIDCSMT
        cookie_domain: ".ween.tn"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
            - 'bootstrap_3_layout.html.twig'
    globals:
            domain: "%domain%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }



fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AdminBundle\Entity\User
    from_email:
        address: 'test@test.com'
        sender_name: 'mailer_user'


hwi_oauth:
    connect:
        confirmation: true
#        account_connector: fos_user.registration.form.factory
#        account_connector: my.custom.user_provider
        registration_form:  fos_user.registration.form.factory

    firewall_names: [main]
    fosub:
        username_iterations: 36000
        properties:
            facebook:    facebook_id
            google:      googleId
    resource_owners:
        facebook:
            type:                facebook
            client_id:           438343659868946
            client_secret:       64a39c8892eecac2dcf72912a512ee1a
            scope:               "email"
            infos_url:     "https://graph.facebook.com/me?fields=id,email,name,first_name,last_name,gender,location,picture,birthday"
            paths:
                    email:            email
                    firstname:      first_name
                    lastname:      last_name
#            scope:               "email, basic_info, user_birthday"
#            infos_url:     "https://graph.facebook.com/me?fields=id,email,first_name,last_name,gender,birthday,location"
            options:
                display: popup #dialog is optimized for popup window
                auth_type: rerequest # Re-asking for Declined Permissions

        google:
            type:                google
            client_id:           765043752128-psnqtiovuaplmm95hkk52fh3bsqh48dm.apps.googleusercontent.com
            client_secret:       m-jWIMEyKXH_9yhmQVLNcRws
            scope:               "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
            options:
                display: popup #dialog is optimized for popup window


knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: 'KnpPaginatorBundle:Pagination:sliding.html.twig'     # sliding pagination controls template
        sortable: 'KnpPaginatorBundle:Pagination:sortable_link.html.twig' # sort link template