<?php

namespace AdminBundle\Repository;

/**
 * CARRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CARRepository extends \Doctrine\ORM\EntityRepository
{
}
