<?php

namespace UserBundle\Repository;
use Doctrine\ORM\Mapping as ORM;



/**
 * userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userRepository extends \Doctrine\ORM\EntityRepository
{

    public function filtreQQui($tag)
    {

        $qb=$this->createQueryBuilder("u");
        $qb->join("u.qville", "qv");
        $qb->join("qv.ville", "v");

        if ($tag["ville"] != null){
            $qb->where("v.libelle like :tag_ville_param")
                ->setParameter('tag_ville_param', "%".$tag["ville"]."%");
        }

        $qb->where("u.name like :tag_param")
            ->setParameter('tag_param', "%".$tag."%");
        return $qb->getQuery()->getResult();

    }


}

