<?php

namespace AdminBundle\Repository;

/**
 * ImmobiliairRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImmobiliairRepository extends \Doctrine\ORM\EntityRepository
{
}
