car_index:
    path:     /
    defaults: { _controller: "AdminBundle:Car:index" }
    methods:  GET

car_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:Car:show" }
    methods:  GET

car_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Car:edit" }
    methods:  [GET, POST]

car_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Car:delete" }
    methods:  DELETE
